name: Run Tests

on:
  push:
    branches: # Se ejecuta en las ramas siguientes      
main
develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      
name: Checkout code
      uses: actions/checkout@v3 # Descarga tu código del repositorio

      
name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18 # Cambia a la versión de Node que uses

      
name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
        restore-keys: |${{ runner.os }}-node-

      
name: Install dependencies
      run: npm install

      
name: Run tests
      run: npm test

      
name: Generate coverage report
      run: npm run test:cov # Esto genera un reporte de cobertura si tenés configurado Jest

      
name: Enforce coverage threshold
      run: |
        echo "Checking test coverage..."
        npm run test:cov || exit 1
